include(FetchContent)
include(Dependency/GSL.cmake)
include(Dependency/GLM.cmake)
include(Dependency/spdlog.cmake)
add_library(Dependency INTERFACE)
target_link_libraries(Dependency INTERFACE gsl)
target_link_libraries(Dependency INTERFACE hookbill-glm)
target_link_libraries(Dependency INTERFACE hookbill-spdlog)
target_compile_features(Dependency INTERFACE cxx_std_17)
